# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-28 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('released', models.DateField()),
                ('runtime', models.CharField(max_length=30)),
                ('genre', models.CharField(max_length=255)),
                ('director', models.CharField(max_length=60)),
                ('writer', models.CharField(max_length=60)),
                ('actors', models.TextField()),
                ('plot', models.TextField()),
                ('language', models.CharField(max_length=20)),
                ('poster', models.URLField()),
                ('meta_score', models.FloatField(default=0)),
                ('rating', models.FloatField(default=0)),
                ('votes', models.FloatField(default=0)),
                ('movie_id', models.CharField(max_length=10)),
                ('media_type', models.CharField(max_length=10)),
                ('media_source', models.CharField(max_length=10)),
                ('price', models.FloatField(default=0)),
            ],
        ),
    ]
